// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBA_API.DAL;

#nullable disable

namespace NBA_API.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NBA_API.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipoId"));

                    b.Property<string>("Conferencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipoId");

                    b.ToTable("Equipo");

                    b.HasData(
                        new
                        {
                            EquipoId = 1,
                            Conferencia = "Oeste",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Los_Angeles_Lakers_logo.svg/640px-Los_Angeles_Lakers_logo.svg.png",
                            Nombre = "Lakers"
                        },
                        new
                        {
                            EquipoId = 2,
                            Conferencia = "Oeste",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/0/01/Golden_State_Warriors_logo.svg/640px-Golden_State_Warriors_logo.svg.png",
                            Nombre = "Warriors"
                        },
                        new
                        {
                            EquipoId = 3,
                            Conferencia = "Este",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/6/67/Chicago_Bulls_logo.svg/200px-Chicago_Bulls_logo.svg.png",
                            Nombre = "Bulls"
                        },
                        new
                        {
                            EquipoId = 4,
                            Conferencia = "Este",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/2/25/New_York_Knicks_logo.svg/1200px-New_York_Knicks_logo.svg.png",
                            Nombre = "Knicks"
                        },
                        new
                        {
                            EquipoId = 5,
                            Conferencia = "Este",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/Boston_Celtics.svg/800px-Boston_Celtics.svg.png",
                            Nombre = "Celtics"
                        },
                        new
                        {
                            EquipoId = 6,
                            Conferencia = "Este",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Miami_Heat_logo.svg/640px-Miami_Heat_logo.svg.png",
                            Nombre = "Heat"
                        },
                        new
                        {
                            EquipoId = 7,
                            Conferencia = "Este",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Brooklyn_Nets_newlogo.svg/800px-Brooklyn_Nets_newlogo.svg.png",
                            Nombre = "Nets"
                        },
                        new
                        {
                            EquipoId = 8,
                            Conferencia = "Oeste",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/Los_Angeles_Clippers_%282024%29.svg/1200px-Los_Angeles_Clippers_%282024%29.svg.png",
                            Nombre = "Clippers"
                        },
                        new
                        {
                            EquipoId = 9,
                            Conferencia = "Oeste",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/2/28/Houston_Rockets.svg/800px-Houston_Rockets.svg.png",
                            Nombre = "Rockets"
                        },
                        new
                        {
                            EquipoId = 10,
                            Conferencia = "Oeste",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/San_Antonio_Spurs.svg/240px-San_Antonio_Spurs.svg.png",
                            Nombre = "Spurs"
                        },
                        new
                        {
                            EquipoId = 11,
                            Conferencia = "Oeste",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Oklahoma_City_Thunder.svg/200px-Oklahoma_City_Thunder.svg.png",
                            Nombre = "Thunder"
                        },
                        new
                        {
                            EquipoId = 12,
                            Conferencia = "Oeste",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/d/dc/Phoenix_Suns_logo.svg/1200px-Phoenix_Suns_logo.svg.png",
                            Nombre = "Suns"
                        },
                        new
                        {
                            EquipoId = 13,
                            Conferencia = "Oeste",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/9/93/TrailBlazers.png",
                            Nombre = "Trail Blazers"
                        },
                        new
                        {
                            EquipoId = 14,
                            Conferencia = "Oeste",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/5/52/Utah_Jazz_logo_2022.svg/230px-Utah_Jazz_logo_2022.svg.png",
                            Nombre = "Jazz"
                        },
                        new
                        {
                            EquipoId = 15,
                            Conferencia = "Este",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/0/02/Washington_Wizards_logo.svg/200px-Washington_Wizards_logo.svg.png",
                            Nombre = "Wizards"
                        },
                        new
                        {
                            EquipoId = 16,
                            Conferencia = "Este",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Logo_of_the_Detroit_Pistons.svg/200px-Logo_of_the_Detroit_Pistons.svg.png",
                            Nombre = "Pistons"
                        },
                        new
                        {
                            EquipoId = 17,
                            Conferencia = "Este",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/c/c4/Charlotte_Hornets_%282014%29.svg/220px-Charlotte_Hornets_%282014%29.svg.png",
                            Nombre = "Hornets"
                        },
                        new
                        {
                            EquipoId = 18,
                            Conferencia = "Este",
                            Imagen = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Cleveland_Cavaliers_logo.svg/170px-Cleveland_Cavaliers_logo.svg.png",
                            Nombre = "Cavaliers"
                        },
                        new
                        {
                            EquipoId = 19,
                            Conferencia = "Este",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Milwaukee_Bucks_logo.svg/180px-Milwaukee_Bucks_logo.svg.png",
                            Nombre = "Bucks"
                        },
                        new
                        {
                            EquipoId = 20,
                            Conferencia = "Este",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/1/10/Orlando_Magic_logo.svg/220px-Orlando_Magic_logo.svg.png",
                            Nombre = "Magic"
                        },
                        new
                        {
                            EquipoId = 21,
                            Conferencia = "Este",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/0/0e/Philadelphia_76ers_logo.svg/200px-Philadelphia_76ers_logo.svg.png",
                            Nombre = "Sixers"
                        },
                        new
                        {
                            EquipoId = 22,
                            Conferencia = "Este",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/2/24/Atlanta_Hawks_logo.svg/200px-Atlanta_Hawks_logo.svg.png",
                            Nombre = "Hawks"
                        },
                        new
                        {
                            EquipoId = 23,
                            Conferencia = "Oeste",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/7/76/Denver_Nuggets.svg/200px-Denver_Nuggets.svg.png",
                            Nombre = "Nuggets"
                        },
                        new
                        {
                            EquipoId = 24,
                            Conferencia = "Oeste",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/9/97/Dallas_Mavericks_logo.svg/210px-Dallas_Mavericks_logo.svg.png",
                            Nombre = "Mavericks"
                        },
                        new
                        {
                            EquipoId = 25,
                            Conferencia = "Oeste",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/Minnesota_Timberwolves_logo.svg/200px-Minnesota_Timberwolves_logo.svg.png",
                            Nombre = "Timberwolves"
                        },
                        new
                        {
                            EquipoId = 26,
                            Conferencia = "Oeste",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/0/0d/New_Orleans_Pelicans_logo.svg/250px-New_Orleans_Pelicans_logo.svg.png",
                            Nombre = "Pelicans"
                        },
                        new
                        {
                            EquipoId = 27,
                            Conferencia = "Oeste",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/SacramentoKings.svg/180px-SacramentoKings.svg.png",
                            Nombre = "Kings"
                        },
                        new
                        {
                            EquipoId = 28,
                            Conferencia = "Este",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/3/36/Toronto_Raptors_logo.svg/200px-Toronto_Raptors_logo.svg.png",
                            Nombre = "Raptors"
                        },
                        new
                        {
                            EquipoId = 29,
                            Conferencia = "Oeste",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Memphis_Grizzlies.svg/190px-Memphis_Grizzlies.svg.png",
                            Nombre = "Grizzlies"
                        },
                        new
                        {
                            EquipoId = 30,
                            Conferencia = "Este",
                            Imagen = "https://upload.wikimedia.org/wikipedia/en/thumb/1/1b/Indiana_Pacers.svg/200px-Indiana_Pacers.svg.png",
                            Nombre = "Pacers"
                        });
                });

            modelBuilder.Entity("NBA_API.Jugador", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JugadorId"));

                    b.Property<double>("AsistenciasporPartido")
                        .HasColumnType("float");

                    b.Property<double>("BloqueosporPartido")
                        .HasColumnType("float");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PuntosporPartido")
                        .HasColumnType("float");

                    b.Property<double>("RebotesporPartido")
                        .HasColumnType("float");

                    b.Property<double>("RobosporPartido")
                        .HasColumnType("float");

                    b.HasKey("JugadorId");

                    b.ToTable("Jugador");
                });
#pragma warning restore 612, 618
        }
    }
}
